version: "3"
services:
    backend:
        build: . 
        image: flaskbackend:v1
        ports:
            - 5000:5000
        container_name: flaskbackend
    mongo:
        image: mongo:4.2.0
        container_name: mongo
        ports:
            - 1048:27017